name: github-api-rate-limit-metrics
description: Send rate limit metrics of GitHub API to Datadog
inputs:
  github-token:
    description: GitHub token
    required: true
  datadog-api-key:
    description: Datadog API key (dry-run if not set)
    required: false
  datadog-tags:
    description: Tags to send to Datadog
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
